### PR TITLE
Belief propagation optimisation

### PR DESCRIPTION
**Pull request by pverscha**

### CODE REVIEW

**Comment by SimonVandeVyver** [comment]
@pverscha : Can you review? I can not assign you as reviewer

**Comment by pverscha** [comment]
@SimonVandeVyver Yes, I'll go through this. I opened this PR, that's probably why I can't be assigned as a reviewer.

**Comment by SimonVandeVyver** [comment]
@pverscha I think there is a small mistake in the `zero_lookahead_belief_propagation` which is marked with a TODO. Can you also look into this?

**Review by pverscha — COMMENTED** [review]
Nice work. Some interesting benchmarking results (tested on `rescored.psms.tsv.gz`):

**Before:**
Time (complete pipeline): 304s
Peak memory: 7653 MiB

**After:**
Time (complete pipeline): 119s
Peak memory: 1137 MiB

Looking very good! Thanks!

**Pull request merged**
